services:
  - type: web
    name: apiwebnews
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-15e46fdf-tuvo-5556.k.aivencloud.com
      - key: DB_PORT
        value: 19487
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_Pki5NnUSN2W7YWmMreu
